name = "gmsh"
uuid = "a3f5b5a8-4c56-11eb-214e-350f4127dda5"
authors = ["Maximilian KÃ¶hler <maximilian.koehler@rub.de>"]
version = "0.1.1"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
gmsh_jll = "630162c2-fc9b-58b3-9910-8442a8a132e6"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
